name: Emil Seman, just a student
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
collections:
  projects:
    output: true
    permalink: /projects/:path/

